version: '2'
services:
  proxy:
    image: nginx:1.13.7-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - 81:80
    networks:
      swagger.loc:
        aliases:
          - proxy.swagger.loc
  swagger-browser:
    container_name: browser
    restart: unless-stopped
    hostname: browser.swagger.loc
    image: node:8.9-alpine
    working_dir: /app
    volumes:
      - $PWD:/app
    command: su node -c "cd /app && npm i && npm run start"
    container_name: browser
    expose:
      - 8080
    networks:
      swagger.loc:
        aliases:
          - browser.swagger.loc
  swagger-ui:
    container_name: swaggerui
    restart: unless-stopped
    hostname: swaggerui.swagger.loc
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://browser.swagger.loc:81/tiptv/swagger.json
    expose:
      - 8080
    networks:
      swagger.loc:
        aliases:
          - swaggerui.swagger.loc
networks:
  swagger.loc:
    external: true
